pipeline {
    agent any
    parameters {
        string(name: 'BRANCH', defaultValue: 'main', description: 'Pass the name of branch to build from ')
        string(name: 'REPO_URL', defaultValue: 'https://github.com/ityourway/learning-jenkins-repo.git', description: 'Pass the Repository url to build from ')
        string(name: 'S3_BUCKET_VERSION',description: 'Enter your preffered VERSION for the s3 bucket, Eg . V001')
        }
    environment { 
        BRANCH = "${params.BRANCH}"
        REPO_URL = "${params.REPO_URL}"
        S3_BUCKET_VERSION = "${params.S3_BUCKET_VERSION}"

    }
    stages {
        stage('Clone GitHub Repo') {
            steps {
                script {
                git branch: "${BRANCH}", credentialsId: 'jenkins-github-creds', url: "${REPO_URL}"
            }
        }
        }
        stage('Create S3 Bucket') {
            steps {
                script {
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'jenkins-aws-creds', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                
                sh "aws s3 mb s3://ITYOURWAY-S3-${S3_BUCKET_VERSION}"
                sh "sleep 60"
                 }
                }           
            }
        }
        stage('Delete S3 Bucket') {
            steps {
                script {
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'jenkins-aws-creds', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                sh """
                aws s3 rb s3://ITYOURWAY-S3-${S3_BUCKET_VERSION}
                """
}
                }
            }
        }
    }
}