pipeline {
    agent any
    parameters {
        string(name: 'BRANCH', defaultValue: 'main', description: 'Pass the name of branch to build from ')
        string(name: 'REPO_URL', defaultValue: 'https://github.com/ityourway/learning-jenkins-repo.git', description: 'Pass the Repository url to build from ')
        string(name: 'S3_BUCKET_NAME',description: 'Enter your preffered name for the s3 bucket')
        }
    stages {
        stage('Clone GitHub Repo') {
            steps {
                script {
                git branch: "${params.BRANCH}", credentialsId: 'jenkins-github-creds', url: "${params.REPO_URL}"
            }
        }
        }
        stage('Create S3 Bucket') {
            steps {
                script {
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'jenkins-aws-creds', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                
                sh "aws s3 mb s3://${params.S3_BUCKET_NAME}"
                sh "sleep 60"
                 }
                }           
            }
        }
        stage('Delete S3 Bucket') {
            steps {
                script {
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'jenkins-aws-creds', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                sh """
                aws s3 rb s3://${params.S3_BUCKET_NAME}
                """
}
                }
            }
        }
    }
}